config/routes.rb
Rails.application.routes.draw do
  resources :assos do
    resources :ateliers
  end
  resources :items
  resources :events
  resources :places
  resources :users
  resources :tools
  resources :metiers
  devise_for :admins, controllers: { sessions: 'admins/sessions' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'root#index' 
  get '/legal', to: 'legal#index'

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/asso.rb
class Asso < ApplicationRecord
	belongs_to :departement
	has_many :events
	has_many :ateliers
end

app/models/atelier.rb
class Atelier < ApplicationRecord
	belongs_to :asso
	belongs_to :place
	belongs_to :metier
end

app/models/departement.rb
class Departement < ApplicationRecord
	belongs_to :region

	def to_s
		numero
	end
end

app/models/event.rb
class Event < ApplicationRecord
	has_and_belongs_to_many :metiers
end

app/models/item.rb
class Item < ApplicationRecord
	has_and_belongs_to_many :metiers
end

app/models/metier.rb
class Metier < ApplicationRecord
	has_and_belongs_to_many :tools
	has_and_belongs_to_many :items
	has_many :users
	has_many :items
	has_many :ateliers
end

app/models/place.rb
class Place < ApplicationRecord
	has_many :events
	has_many :ateliers
end

app/models/region.rb
class Region < ApplicationRecord

	has_many :departements

	def to_s
		displayname
	end
end

app/models/tool.rb
class Tool < ApplicationRecord
	has_and_belongs_to_many :metiers
	has_and_belongs_to_many :items
end

app/models/user.rb
class User < ApplicationRecord
	belongs_to :metier
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def index
  end
end

app/helpers/assos_helper.rb
module AssosHelper
end

app/helpers/ateliers_helper.rb
module AteliersHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/legal_helper.rb
module LegalHelper
end

app/helpers/metiers_helper.rb
module MetiersHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/root/index.html.erb

    <section class="about row align-items-center">
        <div class="text col-md-6 pr-4">
            <h2>Echanger et Transmettre</h2>
            <p>L’initiation des enfants aux métiers manuels et du patrimoine</p>
            <p>L’Outil en Main est né d’un besoin vital: celui de partager. Partager des connaissances, des savoir-faire, mais aussi partager des passions, des valeurs, et des moments dont on se souviendra longtemps. L’Outil en Main, c’est la transmission d’un savoir à travers trois générations: les enfants dès neuf ans découvrent les métiers manuels et artisanaux français auprès de bénévoles, des artisans et des ouvriers retraités qui veulent mettre au profit de tous leurs connaissances. C’est un moment d’échange qui a permis aujourd’hui à plus d’un millier de jeunes de découvrir leur vocation et de s’engager dans la voie de métiers créatifs, et à des bénévoles dans toute la France de partager leur passion et de passer du temps avec leurs pairs et avec la nouvelle génération d’artisans.</p>
            <%= link_to assos_path, class:"btn" do %>
                <svg viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M20.6667 18.6667H19.6133L19.24 18.3067C20.5467 16.7867 21.3333 14.8133 21.3333 12.6667C21.3333 7.88 17.4533 4 12.6667 4C7.88 4 4 7.88 4 12.6667C4 17.4533 7.88 21.3333 12.6667 21.3333C14.8133 21.3333 16.7867 20.5467 18.3067 19.24L18.6667 19.6133V20.6667L25.3333 27.32L27.32 25.3333L20.6667 18.6667ZM12.6667 18.6667C9.34667 18.6667 6.66667 15.9867 6.66667 12.6667C6.66667 9.34667 9.34667 6.66667 12.6667 6.66667C15.9867 6.66667 18.6667 9.34667 18.6667 12.6667C18.6667 15.9867 15.9867 18.6667 12.6667 18.6667Z" fill="white"/></svg>
                Trouver une association</a>
            <% end %>
        </div>
        <div class="image col-md-6">
            <img src="https://www.loutilenmain.fr/main/pages/medias-presse/RootAlbums/Foire%20de%20Rennes%202019/20190329011.jpg" class="img-full" alt="" srcset="">
        </div>
    </section>
    <section class="meters row">
        <div class="col-12">
            <h2>Découvrez nos différents métiers</h2>
            <div class="row" style="max-height: 240px; overflow: hidden;">
                <div class="col-md-4">
                    <img src="https://cdn.pixabay.com/photo/2017/06/09/04/02/wood-working-2385634_1280.jpg" class="img-full" alt="" srcset="">
                </div>
                <div class="col-md-4">
                    <img src="https://cdn.pixabay.com/photo/2017/06/09/04/02/wood-working-2385634_1280.jpg" class="img-full" alt="" srcset="">
                </div>
                <div class="col-md-4">
                    <img src="https://cdn.pixabay.com/photo/2017/06/09/04/02/wood-working-2385634_1280.jpg" class="img-full" alt="" srcset="">
                </div>
            </div>
            <div class="showall">
                <%= link_to metiers_path, class:"btn" do %>
                    <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M1.00007 21H13.0001V23H1.00007V21ZM5.24507 8.07L8.07507 5.243L22.2151 19.385L19.3871 22.213L5.24507 8.07ZM12.3171 1L17.9741 6.656L15.1441 9.486L9.49007 3.826L12.3171 1ZM3.82507 9.485L9.48207 15.142L6.65407 17.97L0.99707 12.313L3.82507 9.485Z" fill="white"/></svg>
                    Tous les métiers
                <% end %>
            </div>
        </div>
    </section>
    <section class="benevoles">
        <div class="row align-items-center">
            <div class="col-md-6 pr-4">
                <h2>Accompagné par des bénévoles passionnés</h2>
                <p>Les métiers manuels ont une longue histoire de transmission de maître à élève. Quoi de plus naturel que de prolonger cette tradition en permettant à des artisans et ouvriers retraités de continuer à partager leurs savoirs ? Les bénévoles de L’Outil en Main sont des gens de métiers qualifiés, mais ce sont avant tout des passionnés, qui aiment leur travail et veulent le transmettre. Ces hommes et ces femmes apportent un véritable enrichissement à la fois humain et technique aux enfants à qui ils enseignent, et c’est une expérience épanouissante pour les jeunes comme pour les retraités.</p>

                <%= link_to users_path, class:"btn" do %>
                    <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M12 4.5C7 4.5 2.73 7.61 1 12C2.73 16.39 7 19.5 12 19.5C17 19.5 21.27 16.39 23 12C21.27 7.61 17 4.5 12 4.5ZM12 17C9.24 17 7 14.76 7 12C7 9.24 9.24 7 12 7C14.76 7 17 9.24 17 12C17 14.76 14.76 17 12 17ZM12 9C10.34 9 9 10.34 9 12C9 13.66 10.34 15 12 15C13.66 15 15 13.66 15 12C15 10.34 13.66 9 12 9Z" fill="white"/></svg>
                    Découvrez nos bénévoles
                <% end %>
                <%= link_to users_path, class:"btn" do %>
                    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M12 2C6.48 2 2 6.48 2 12C2 17.52 6.48 22 12 22C17.52 22 22 17.52 22 12C22 6.48 17.52 2 12 2ZM13 19H11V17H13V19ZM15.07 11.25L14.17 12.17C13.45 12.9 13 13.5 13 15H11V14.5C11 13.4 11.45 12.4 12.17 11.67L13.41 10.41C13.78 10.05 14 9.55 14 9C14 7.9 13.1 7 12 7C10.9 7 10 7.9 10 9H8C8 6.79 9.79 5 12 5C14.21 5 16 6.79 16 9C16 9.88 15.64 10.68 15.07 11.25Z" fill="white"/></svg>
                    Devenir bénévole
                <% end %>         
            </div>
            <div class="col-md-6">
                <div class="row mt-4 mb-4">
                    <div class="col-4"><img src="https://vz.cnwimg.com/thumb-1200x/wp-content/uploads/2018/06/bb.jpg" class="img-full" alt=""></div>
                    <div class="col-4"><img src="https://www.stenphoto.fr/wp-content/uploads/2019/05/StenBySB.jpg" class="img-full" alt=""></div>
                    <div class="col-4"><img src="https://vz.cnwimg.com/thumb-1200x/wp-content/uploads/2018/06/bb.jpg" class="img-full" alt=""></div>
                </div>
            </div>
        </div>
    </section>
    <section class="tools">
        <div class="row align-items-center">
            <div class="col-md-6">
                <%= image_tag "adult-1866533_1920.jpg", alt: "", class: "img-full"%>
            </div>
            <div class="col-md-6  pl-4">
                <h2>Apprenez à manier des outils de professionel</h2>
                <p>Burin, pied à coulisse, rabot, fuseau… Tous ces objets peu connu du grand public sont les outils de travail que les artisans et ouvriers utilisent quotidiennement. Avec L’Outil en Main, vous pourrez développer votre habileté manuelle en apprenant à les manipuler et vous en servir pour créer des objets de toutes sortes.</p>
                <%= link_to tools_path, class:"btn" do %>
                    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M22.6999 18.9998L13.5999 9.89977C14.4999 7.59977 13.9999 4.89977 12.0999 2.99977C10.0999 0.999768 7.09994 0.599768 4.69994 1.69977L8.99994 5.99977L5.99994 8.99977L1.59994 4.69977C0.399939 7.09977 0.899939 10.0998 2.89994 12.0998C4.79994 13.9998 7.49994 14.4998 9.79994 13.5998L18.8999 22.6998C19.2999 23.0998 19.8999 23.0998 20.2999 22.6998L22.5999 20.3998C23.0999 19.9998 23.0999 19.2998 22.6999 18.9998Z" fill="white"/></svg>
                    Liste des outils
                <% end %>
            </div> 
        </div>
    </section>
    <section class="creations">
        <div class="row">
            <div class="col-md-6">
                <h2>Réalisez des créations épatantes</h2>
                <p>Qui n’a jamais rêvé d’utiliser au quotidien des objets faits par ses propres mains ? Ici, les bénévoles accompagnent les enfants dans la découverte d’une activité manuelle et la fabrication d’objets uniques, de la conception à la réalisation. Les enfants pourront ramener chez eux un nichoir, une étagère à épices, un pot à crayon en mosaïque, ou encore une pendule en fer forgé. Un souvenir unique et précieux de leur propre créativité et leur savoir-faire.</p>
            </div>
            <div class="col-md-12 text-center">
                <div class="row">
                    <div class="col-md-3"><img src="https://www.loutilenmain.fr/ged/bibliobjets/2570.jpg" class="img-full" alt=""></div>
                    <div class="col-md-3"><img src="https://www.loutilenmain.fr/ged/bibliobjets/2570.jpg" class="img-full" alt=""></div>
                    <div class="col-md-3"><img src="https://www.loutilenmain.fr/ged/bibliobjets/2570.jpg" class="img-full" alt=""></div>
                    <div class="col-md-3"><img src="https://www.loutilenmain.fr/ged/bibliobjets/2570.jpg" class="img-full" alt=""></div>
                </div>
                <%= link_to items_path, class:"btn" do %>
                    <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M10 11.9999V19.9999H18V11.9999H10ZM0 19.9999H8V11.9999H0V19.9999ZM0 1.99994V9.99994H8V1.99994H0ZM13.66 0.689941L8 6.33994L13.66 11.9999L19.32 6.33994L13.66 0.689941V0.689941Z" fill="white"/></svg>
                    Liste des réalisations
                <% end %>
            </div>
        </div>
    </section>