config/routes.rb
Rails.application.routes.draw do
  resources :assos do
    resources :ateliers
  end
  resources :items
  resources :events
  resources :places
  resources :users
  resources :tools
  resources :metiers
  devise_for :admins, controllers: { sessions: 'admins/sessions' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'root#index' 
  get '/legal', to: 'legal#index'

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/asso.rb
class Asso < ApplicationRecord
	belongs_to :departement
	has_many :events
	has_many :ateliers
end

app/models/atelier.rb
class Atelier < ApplicationRecord
	belongs_to :asso
	belongs_to :place
	belongs_to :metier
end

app/models/departement.rb
class Departement < ApplicationRecord
	belongs_to :region

	def to_s
		numero
	end
end

app/models/event.rb
class Event < ApplicationRecord
	has_and_belongs_to_many :metiers
end

app/models/item.rb
class Item < ApplicationRecord
	has_and_belongs_to_many :metiers
end

app/models/metier.rb
class Metier < ApplicationRecord
	has_and_belongs_to_many :tools
	has_and_belongs_to_many :items
	has_many :users
	has_many :items
	has_many :ateliers
end

app/models/place.rb
class Place < ApplicationRecord
	has_many :events
	has_many :ateliers
end

app/models/region.rb
class Region < ApplicationRecord

	has_many :departements

	def to_s
		displayname
	end
end

app/models/tool.rb
class Tool < ApplicationRecord
	has_and_belongs_to_many :metiers
	has_and_belongs_to_many :items
end

app/models/user.rb
class User < ApplicationRecord
	belongs_to :metier
end

app/controllers/assos_controller.rb
class AssosController < ApplicationController
  before_action :set_asso, only: [:show, :edit, :update, :destroy]
  add_breadcrumb "Associations", :assos_path

  # GET /assos
  # GET /assos.json
  def index
    @regions = Region.all
    @departements = Departement.all
    @assos = Asso.all
  end

  # GET /assos/1
  # GET /assos/1.json
  def show
    add_breadcrumb "#{@asso.name}", :asso_path
  end

  # GET /assos/new
  def new
    @asso = Asso.new
  end

  # GET /assos/1/edit
  def edit
  end

  # POST /assos
  # POST /assos.json
  def create
    @asso = Asso.new(asso_params)

    respond_to do |format|
      if @asso.save
        format.html { redirect_to @asso, notice: 'Asso was successfully created.' }
        format.json { render :show, status: :created, location: @asso }
      else
        format.html { render :new }
        format.json { render json: @asso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assos/1
  # PATCH/PUT /assos/1.json
  def update
    respond_to do |format|
      if @asso.update(asso_params)
        format.html { redirect_to @asso, notice: 'Asso was successfully updated.' }
        format.json { render :show, status: :ok, location: @asso }
      else
        format.html { render :edit }
        format.json { render json: @asso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assos/1
  # DELETE /assos/1.json
  def destroy
    @asso.destroy
    respond_to do |format|
      format.html { redirect_to assos_url, notice: 'Asso was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_asso
      @asso = Asso.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def asso_params
      params.require(:asso).permit(:name, :address, :zipcode, :city, :lat, :long, :phone, :email, :members, :departement_id)
    end
end

app/helpers/assos_helper.rb
module AssosHelper
end

app/helpers/ateliers_helper.rb
module AteliersHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/legal_helper.rb
module LegalHelper
end

app/helpers/metiers_helper.rb
module MetiersHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/assos/_form.html.erb
<%= simple_form_for(@asso) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :zipcode %>
    <%= f.input :city %>
    <%= f.input :lat %>
    <%= f.input :long %>
    <%= f.input :phone %>
    <%= f.input :email %>
    <%= f.input :members %>
    <%= f.association :departement %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/assos/edit.html.erb
<h1>Editing Asso</h1>

<%= render 'form', asso: @asso %>

<%= link_to 'Show', @asso %> |
<%= link_to 'Back', assos_path %>

app/views/assos/index.html.erb
<h1 class="h2">Nos associations</h1>
<div class="row">
  <div class="col-auto my-1">
      <label class="mr-sm-2" for="regionSelect">Région</label>
      <select class="custom-select mr-sm-2" id="regionSelect">
        <option value="-1" selected>Toutes</option>
         <% @regions.each do |region| %>
          <option value="<%= region.num %>"><%= region.displayname %></option>
        <% end %>
      </select>
  </div>
  <div class="col-auto my-1">
      <label class="mr-sm-2" for="departementSelect">Département</label>
      <select class="custom-select mr-sm-2" id="departementSelect">
        <option value="-1" selected>Tous</option>
         <% @departements.each do |departement| %>
          <option value="<%= departement.name %>" data-reg="<%= departement.region.num %>"><%= departement.numero %></option>
        <% end %>
      </select>
  </div>
  <div class="col-md-12 mt-4 mb-4">
    <% @assos.each do |asso| %>
      <%= link_to asso do %>
        <div class="card asso" data-dep="<%= asso.departement.name %>">
          <div class="card-body">
            <p class="h3 card-title"><%= asso.name %></p>
            <p class="card-subtitle text-muted"><%= asso.departement %></p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/assos/new.html.erb
<h1>New Asso</h1>

<%= render 'form', asso: @asso %>

<%= link_to 'Back', assos_path %>

app/views/assos/show.html.erb
<h1 class="h1"><%= @asso.name %></h1>
<h2 class="h2"><%= @asso.departement %></h2>

<div class="col-md-12 text-center mt-5">
  <h2 class="h2">Retrouvez les ateliers !</h2>
  <p>Tous les mercredis de 14H à 18H.</p>
  
  <div class="row">
    <% @asso.ateliers.each do |atelier| %>
      <%= link_to asso_atelier_path(@asso, atelier), class: "col-md-4 p-2" do %>
        <div style="height: 25vw;">
          <img src="https://www.condat.fr/wp-content/uploads/2016/04/lubrifiants-poudres-fils-soudure-660x330.png" class="img-full">
          <div class="position-absolute w-100 h-100 p-2" style="top: 0; left: 0;">
            <p class="h2 h-100 text-white d-flex justify-content-center align-items-center" style="background-color: #343a4080"><%= atelier.name %></p>
          </div>
        </div>
      <% end %>
    <% end %>     
  </div>
  <%= link_to asso_ateliers_path(@asso), class:"btn" do %>
    <span class="glyphicon glyphicon-briefcase" aria-hidden="true"></span> Tous les ateliers
  <% end %>
</div>

<div class="text-center mt-5 col-md-12">
  <h2 class="h2">Découvrez nos réalisations !</h2>
  <p>Tout est fait avec passion !</p>
  <div class="row mt-4 mb-4">
    <div class="col-md-4 mb-2" style="max-height: 15vw;">
      <img src="https://www.loutilenmain.fr/ged/bibliobjets/366.png" class="img-full">
    </div>
    <div class="col-md-4 mb-2" style="max-height: 15vw;">
      <img src="https://www.loutilenmain.fr/ged/bibliobjets/3223.jpg" class="img-full">
    </div>
    <div class="col-md-4 mb-2" style="max-height: 15vw;">
      <img src="https://www.loutilenmain.fr/ged/bibliobjets/2570.jpg" class="img-full">
    </div>
  </div>
  <%= link_to 'Liste des réalisations', items_path, class:"btn"%>
</div>

<div class="col-md-12 mt-5">
  <h2 class="h2 text-center">L'Association</h2>
  <h3 class="h3 text-center">Contactez-nous</h3>
  <div class="row mt-5 mb-5">
    <div class="col-md-5 pr-md-4">
        <img src="https://cutt.ly/NtLMJYm" class="img-full">
    </div>
    <div class="col-md-7">
        <h2 class="h3">Responsable</h2>
        <p class="mb-4">Jacques Laurentin</p>
        <h2 class="h3">Adresse de l'association</h2>
        <p><%= @asso.address %></p>
        <p class="mb-4"><%= @asso.zipcode %> <%= @asso.city %></p> 
        <h2 class="h3">Contacter l'association</h2>
        <p>Par E-mail : <%= @asso.email %></p>
        <p>Par téléphone : <%= @asso.phone %></p>
    </div>
  </div>
</div>