config/routes.rb
Rails.application.routes.draw do
  resources :assos do
    resources :ateliers
  end
  resources :items
  resources :events
  resources :places
  resources :users
  resources :tools
  resources :metiers
  devise_for :admins, controllers: { sessions: 'admins/sessions' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'root#index' 
  get '/legal', to: 'legal#index'

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/asso.rb
class Asso < ApplicationRecord
	belongs_to :departement
	has_many :events
	has_many :ateliers
end

app/models/atelier.rb
class Atelier < ApplicationRecord
	belongs_to :asso
	belongs_to :place
	belongs_to :metier
end

app/models/departement.rb
class Departement < ApplicationRecord
	belongs_to :region

	def to_s
		numero
	end
end

app/models/event.rb
class Event < ApplicationRecord
	has_and_belongs_to_many :metiers
end

app/models/item.rb
class Item < ApplicationRecord
	has_and_belongs_to_many :metiers
end

app/models/metier.rb
class Metier < ApplicationRecord
	has_and_belongs_to_many :tools
	has_and_belongs_to_many :items
	has_many :users
	has_many :items
	has_many :ateliers
end

app/models/place.rb
class Place < ApplicationRecord
	has_many :events
	has_many :ateliers
end

app/models/region.rb
class Region < ApplicationRecord

	has_many :departements

	def to_s
		displayname
	end
end

app/models/tool.rb
class Tool < ApplicationRecord
	has_and_belongs_to_many :metiers
	has_and_belongs_to_many :items
end

app/models/user.rb
class User < ApplicationRecord
	belongs_to :metier
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]
  add_breadcrumb "Lieux", :places_path

  # GET /places
  # GET /places.json
  def index
    @places = Place.all
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def place_params
      params.require(:place).permit(:name, :address, :zipcode, :city, :lat, :long, :phone, :region, :infos)
    end
end

app/helpers/assos_helper.rb
module AssosHelper
end

app/helpers/ateliers_helper.rb
module AteliersHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/legal_helper.rb
module LegalHelper
end

app/helpers/metiers_helper.rb
module MetiersHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/places/_form.html.erb
<%= simple_form_for(@place) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :zipcode %>
    <%= f.input :city %>
    <%= f.input :lat %>
    <%= f.input :long %>
    <%= f.input :phone %>
    <%= f.input :region %>
    <%= f.input :infos %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Editing Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Places</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Zipcode</th>
      <th>City</th>
      <th>Lat</th>
      <th>Long</th>
      <th>Phone</th>
      <th>Region</th>
      <th>Infos</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= place.name %></td>
        <td><%= place.address %></td>
        <td><%= place.zipcode %></td>
        <td><%= place.city %></td>
        <td><%= place.lat %></td>
        <td><%= place.long %></td>
        <td><%= place.phone %></td>
        <td><%= place.region %></td>
        <td><%= place.infos %></td>
        <td><%= link_to 'Show', place %></td>
        <td><%= link_to 'Edit', edit_place_path(place) %></td>
        <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Place', new_place_path %>

app/views/places/new.html.erb
<h1>New Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @place.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @place.address %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @place.zipcode %>
</p>

<p>
  <strong>City:</strong>
  <%= @place.city %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @place.lat %>
</p>

<p>
  <strong>Long:</strong>
  <%= @place.long %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @place.phone %>
</p>

<p>
  <strong>Region:</strong>
  <%= @place.region %>
</p>

<p>
  <strong>Infos:</strong>
  <%= @place.infos %>
</p>

<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Back', places_path %>